### ISSUE TITLE
New Spex release question

### ISSUE THREAD

**Issue by rvbinder** [Faustria/SpecExplorer2010Reviver#22]
Microsoft has published SpecExplorer.9520.msi, which claims to be upgraded for Windows 10 and VS 2017. 
https://www.microsoft.com/en-us/download/details.aspx?id=52461

It installs without complaint, but I don't see anything new.  

@Faustria  - agree with your wiki comments and would like to revive Spex.  Let's discuss offline - rvbinder at gmail dot com.

**Comment by Faustria** [comment]
Hi Bob,
Yes the link is misleading and points to the old Spec Explorer 1.0 which is sharing only few (if any) DNA with the latest Spec Explorer 3.5.3146.0. we use here.

**Comment by Faustria** [comment]
Phil Scrace has proposed a new procedure how to install Spec Explorer 2010 with 
Visual Studio Professional 2013 up to 2019. You can find the procedure here: 

[https://softwareengineer1.blogspot.com/2019/02/spec-explorer-lives-getting-spec.html](https://softwareengineer1.blogspot.com/2019/02/spec-explorer-lives-getting-spec.html)

Unfortunately I was not successful with the community edition or professional edition 2019 - 
the mentioned 'Extensions and extensibility' feature is not available. Hope this can help you.
